"""Validadores compartidos por rutas y servicios."""

from __future__ import annotations

import re

_EMAIL_PATTERN = re.compile(
    r"^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$"
)
_USERNAME_PATTERN = re.compile(r"^[a-z0-9._-]{5,32}$")


def is_valid_email(value: str) -> bool:
    """Valida el formato común usado por registro y administración."""
    return bool(_EMAIL_PATTERN.fullmatch(value))


def normalize_username(value: str) -> str:
    """Return the canonical form used for public usernames and ownership keys."""
    return value.strip().lower()


def is_valid_username(value: str) -> bool:
    """Validate a public username (5-32 lowercase basic characters, no email)."""
    normalized = normalize_username(value)
    if not _USERNAME_PATTERN.fullmatch(normalized):
        return False
    # Guest identities are generated by the server and must never be claimable.
    return normalized != "guest" and not normalized.startswith("guest_")
